project:
  type: website
  output-dir: docs
website:
  title: "High005"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Discover"
        href: tutorials.qmd
      - text: "Click to solve together"
        href: jobs.qmd
      - text: "About"
        href: about.qmd
      - text: "Fresh tech"
        href: tech.qmd
      - text: "Analytics tips"
        href: science.qmd