project:
  type: website

website:
  title: "High005"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorials"
        href: tutorials.qmd
      - text: "Tools"
        href: tools.qmd
      - text: "About"
        href: about.qmd
      - text: "Jobs"
        href: jobs.qmd


